//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GetValuesEntities : DbContext
    {
        public GetValuesEntities()
            : base("name=GetValuesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetReportDailyJob_Result> GetReportDailyJob(Nullable<System.DateTime> startdate, Nullable<System.DateTime> endDate, Nullable<System.Guid> workgroupid)
        {
            var startdateParameter = startdate.HasValue ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var workgroupidParameter = workgroupid.HasValue ?
                new ObjectParameter("workgroupid", workgroupid) :
                new ObjectParameter("workgroupid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReportDailyJob_Result>("GetReportDailyJob", startdateParameter, endDateParameter, workgroupidParameter);
        }
    }
}
