//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace connect
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QMEntities : DbContext
    {
        public QMEntities()
            : base("name=QMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetAllWorkGroups_Result> GetAllWorkGroups()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllWorkGroups_Result>("GetAllWorkGroups");
        }
    
        public virtual ObjectResult<GetReport_Result> GetReport(Nullable<System.DateTime> startdate, Nullable<System.DateTime> endDate, Nullable<System.Guid> workgroupid)
        {
            var startdateParameter = startdate.HasValue ?
                new ObjectParameter("startdate", startdate) :
                new ObjectParameter("startdate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("endDate", endDate) :
                new ObjectParameter("endDate", typeof(System.DateTime));
    
            var workgroupidParameter = workgroupid.HasValue ?
                new ObjectParameter("workgroupid", workgroupid) :
                new ObjectParameter("workgroupid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReport_Result>("GetReport", startdateParameter, endDateParameter, workgroupidParameter);
        }
    
        public virtual ObjectResult<GetReportcsvList_Result> GetReportcsvList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReportcsvList_Result>("GetReportcsvList");
        }
    
        public virtual int InsertReport(string reportGeneratedFileName, Nullable<System.DateTime> createdOn, string createdBy, string methodofCreation, string reportGeneratedFullPath, string reportLocation)
        {
            var reportGeneratedFileNameParameter = reportGeneratedFileName != null ?
                new ObjectParameter("ReportGeneratedFileName", reportGeneratedFileName) :
                new ObjectParameter("ReportGeneratedFileName", typeof(string));
    
            var createdOnParameter = createdOn.HasValue ?
                new ObjectParameter("CreatedOn", createdOn) :
                new ObjectParameter("CreatedOn", typeof(System.DateTime));
    
            var createdByParameter = createdBy != null ?
                new ObjectParameter("CreatedBy", createdBy) :
                new ObjectParameter("CreatedBy", typeof(string));
    
            var methodofCreationParameter = methodofCreation != null ?
                new ObjectParameter("MethodofCreation", methodofCreation) :
                new ObjectParameter("MethodofCreation", typeof(string));
    
            var reportGeneratedFullPathParameter = reportGeneratedFullPath != null ?
                new ObjectParameter("ReportGeneratedFullPath", reportGeneratedFullPath) :
                new ObjectParameter("ReportGeneratedFullPath", typeof(string));
    
            var reportLocationParameter = reportLocation != null ?
                new ObjectParameter("ReportLocation", reportLocation) :
                new ObjectParameter("ReportLocation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertReport", reportGeneratedFileNameParameter, createdOnParameter, createdByParameter, methodofCreationParameter, reportGeneratedFullPathParameter, reportLocationParameter);
        }
    }
}
